---
esphome:
  platformio_options:
    # Unset option set by https://github.com/espressif/arduino-esp32/blob/2.0.5/platform.txt#L33
    build_unflags:
      - -std=gnu++11
    # Enable C++17
    build_flags:
      - -std=gnu++1z
  on_boot:
    priority: -100
    then:
      lambda: id(ledc_display_backlight).set_level(1.0);

esp32:
  board: esp32dev

output:
  - platform: ledc
    pin: 4
    id: ledc_display_backlight
    frequency: 19531Hz  # 12-bit depth

light:
  - platform: monochromatic
    name: "${friendly_shortname} Display Backlight"
    id: light_display_backlight
    output: ledc_display_backlight
    # Control and transition in perceptual brightness space, not duty cycle
    gamma_correct: 2.8  # Default value, but make it explicit

spi:
  - id: spi_bus_0
    clk_pin: 18
    mosi_pin: 19
