esphome:
  platform: ESP32
  board: esp32dev

binary_sensor:
  - platform: gpio
    id: gpio_s1
    name: "Button S1"
    pin:
      number: 0
      inverted: True
  - platform: gpio
    id: gpio_s2
    name: "Button S2"
    pin:
      number: 35
      inverted: True

spi:
  - id: spi_bus_0
    clk_pin: 18
    mosi_pin: 19
