packages:
  site: !include site.yaml
  board: !include board_ttgo_t-display.yaml
  product: !include product_iaq_monitor.yaml

esphome:
  name: ${esphome_name}
  comment: ${esphome_comment}
  build_path: ./build/${esphome_name}
  platformio_options:
    # Unset option set by https://github.com/espressif/arduino-esp32/blob/idf-release/v4.0/platform.txt#L31
    build_unflags: -std=gnu++11
    # Enable C++17
    build_flags: -std=gnu++1z
    # Force the use of a newer ESP32 toolchain, which also requires a dev branch
    # of arduino-esp32 that's compatible with ESP-IDF 4 (3.3 contained only GCC
    # 5.2.0, which had poor C++17 support)
    platform_packages: |

      	toolchain-xtensa32 @ >2.80200.200827
      	framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#idf-release/v4.0

time:
  - platform: homeassistant
    id: time_esp
    # Set display brightness by time of day
    on_time:
      - seconds: 0
        minutes: /1
        hours: 8-20
        then:
          lambda: id(ledc_display_backlight).set_level(0.5);
      - seconds: 0
        minutes: /1
        hours: 21-7
        then:
          lambda: id(ledc_display_backlight).set_level(0.05);

# TODO(xo): Move display block into board config
display:
  - platform: st7789v
    # Real backlight is controlled using ledc_display_backlight but this key is
    # required, so use GPIO12 as a dummy value.
    backlight_pin: 12
    cs_pin: 5
    dc_pin: 16
    reset_pin: 23
    lambda: |-
      it.print(0, 0, id(callunasans_24), "Hello, World!");

font:
  - file: "CallunaSans-Regular.ttf"
    id: callunasans_48
    size: 48

  - file: "CallunaSans-Regular.ttf"
    id: callunasans_24
    size: 24

  - file: "CallunaSans-Regular.ttf"
    id: callunasans_12
    size: 12
