packages:
  site: !include site.yaml
  board: !include board_ttgo_t-display.yaml
  product: !include product_iaq_monitor.yaml

esphome:
  name: ${esphome_name}
  comment: ${esphome_comment}
  build_path: ./build/${esphome_name}

time:
  - platform: homeassistant
    id: time_esp
    # Set display brightness by time of day
    on_time:
      - seconds: 0
        minutes: /1
        hours: 8-20
        then:
          lambda: id(ledc_display_backlight).set_level(0.5);
      - seconds: 0
        minutes: /1
        hours: 21-7
        then:
          lambda: id(ledc_display_backlight).set_level(0.05);

# TODO(xo): Move display block into board config
display:
  - platform: st7789v
    # Real backlight is controlled using ledc_display_backlight but this key is
    # required, so use GPIO12 as a dummy value.
    backlight_pin: 12
    cs_pin: 5
    dc_pin: 16
    reset_pin: 23
    lambda: |-
      it.print(0, 0, id(callunasans_24), "Hello, World!");

font:
  - file: "CallunaSans-Regular.ttf"
    id: callunasans_48
    size: 48

  - file: "CallunaSans-Regular.ttf"
    id: callunasans_24
    size: 24

  - file: "CallunaSans-Regular.ttf"
    id: callunasans_12
    size: 12
