packages:
  site: !include site.yaml
  board: !include board_ttgo_t-display.yaml

esphome:
  name: ${esphome_name}
  comment: ${esphome_comment}

time:
  - platform: homeassistant
    id: time_esp

# TODO(xo): Move display block into board config
display:
  - platform: st7789v
    backlight_pin: GPIO4
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    lambda: |-
      it.print(0, 0, id(callunasans_24), "Hello, World!");

font:
  - file: "CallunaSans-Regular.ttf"
    id: callunasans_48
    size: 48
  - file: "CallunaSans-Regular.ttf"
    id: callunasans_24
    size: 24
  - file: "CallunaSans-Regular.ttf"
    id: callunasans_12
    size: 12
