packages:
  site: !include site.yaml
  board: !include board_ttgo_t-display.yaml
  product: !include product_iaq_monitor.yaml

esphome:
  name: ${esphome_name}
  comment: ${esphome_comment}
  build_path: ./build/${esphome_name}

time:
  - platform: homeassistant
    id: time_esp

# TODO(xo): Move display block into board config
display:
  - platform: st7789v
    backlight_pin: 4
    cs_pin: 5
    dc_pin: 16
    reset_pin: 23
    lambda: |-
      it.print(0, 0, id(callunasans_24), "Hello, World!");

font:
  - file: "CallunaSans-Regular.ttf"
    id: callunasans_48
    size: 48
  - file: "CallunaSans-Regular.ttf"
    id: callunasans_24
    size: 24
  - file: "CallunaSans-Regular.ttf"
    id: callunasans_12
    size: 12
