---
packages:
  site: !include site.yaml
  board: !include board_ttgo_t-display.yaml
  product: !include product_iaq_monitor.yaml

esphome:
  name: ${esphome_name}
  comment: ${esphome_comment}
  build_path: ./build/${esphome_name}
  includes:  # Only included into main sketch
    - display.h
  platformio_options:
    # Override platform in order to unpin version set by ESPHome generator
    platform: espressif32
    # Unset option set by https://github.com/espressif/arduino-esp32/blob/idf-release/v4.0/platform.txt#L31
    build_unflags: -std=gnu++11
    # Enable C++17
    build_flags: -std=gnu++1z
    # Force the use of a newer ESP32 toolchain, which also requires a dev branch
    # of arduino-esp32 that's compatible with ESP-IDF 4 (3.3 contained only GCC
    # 5.2.0, which had poor C++17 support)
    platform_packages: |

      	toolchain-xtensa32 @ >2.80200.200827
      	framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#idf-release/v4.0

time:
  - platform: homeassistant
    id: time_esp
    # Set display brightness by time of day
    on_time:
      - seconds: 0
        minutes: /1
        hours: 8-20
        then:
          lambda: id(ledc_display_backlight).set_level(0.5);
      - seconds: 0
        minutes: /1
        hours: 21-23, 0-7
        then:
          lambda: id(ledc_display_backlight).set_level(0.05);

# TODO(xo): Move display and buttons blocks into board config, keeping only
# application logic (page rendering and navigation)
display:
  - platform: st7789v
    # Real backlight is controlled using ledc_display_backlight but this key is
    # required, so use GPIO12 as a dummy value.
    backlight_pin: 12
    cs_pin: 5
    dc_pin: 16
    reset_pin: 23
    id: display_front
    pages:
      - lambda: DrawPage(it, 0);
      - lambda: DrawPage(it, 1);
      - lambda: DrawPage(it, 2);

binary_sensor:
  - platform: gpio
    id: gpio_s1
    name: "${friendly_shortname} Button S1"
    internal: true
    pin:
      number: 0
      inverted: true
    on_release:
      then:
        - display.page.show_previous: display_front
        - component.update: display_front

  - platform: gpio
    id: gpio_s2
    name: "${friendly_shortname} Button S2"
    internal: true
    pin:
      number: 35
      inverted: true
    on_release:
      then:
        - display.page.show_next: display_front
        - component.update: display_front

font:
  - file: "CallunaSansRegular.ttf"
    id: font_sans_48
    size: 48
    glyphs: &font_glyphs
      # Include both μ (U+03BC Greek Small Letter Mu) and µ (U+00B5 Micro Sign)
      ' !"%()+,-./0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ:abcdefghijklmnopqrstuvwxyz_μµ°²³₂'

  - file: "CallunaSansRegular.ttf"
    id: font_sans_34
    size: 34
    glyphs: *font_glyphs

  - file: "CallunaSansRegular.ttf"
    id: font_sans_24
    size: 24
    glyphs: *font_glyphs

  - file: "CallunaSansRegular.ttf"
    id: font_sans_17
    size: 17
    glyphs: *font_glyphs

  - file: "CallunaSansRegular.ttf"
    id: font_sans_12
    size: 12
    glyphs: *font_glyphs
