i2c:
  - id: i2c_bus_0
    sda: 21
    scl: 22
  - id: i2c_bus_1
    sda: 37
    scl: 38

uart:
  - id: uart_bus_0
    rx_pin: GPIO26
    tx_pin: GPIO27
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 1

sensor:
  - platform: scd30
    i2c_id: i2c_bus_0
    co2:
      name: "${friendly_shortname} SCD30 CO₂ Concentration"
      filters:
        &scd30-common-filters
        - exponential_moving_average:
            alpha: 0.4
            send_every: 5
    temperature:
      name: "${friendly_shortname} SCD30 Temperature"
      filters: *scd30-common-filters
    humidity:
      name: "${friendly_shortname} SCD30 Humidity"
      filters: *scd30-common-filters
    update_interval: 2s
  - platform: pmsx003
    type: PMSX003
    uart_id: uart_bus_0
    pm_1_0:
      name: "${friendly_shortname} PM <1.0µm Concentration"
      id: iaq_pm_1_0
      filters:
        &pmsx003-common-filters
        - exponential_moving_average:
            alpha: 0.2
            send_every: 10
    pm_2_5:
      name: "${friendly_shortname} PM 1.0–2.5µm Concentration"
      id: iaq_pm_2_5
      filters: *pmsx003-common-filters
    pm_10_0:
      name: "${friendly_shortname} PM 2.5–10.0µm Concentration"
      id: iaq_pm_10_0
      filters: *pmsx003-common-filters
